name: Deploy Node.js to Azure Web App

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: DatingAppGUI2023 # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "./dist/client" # set this to the path to your web app project
  NODE_VERSION: "18.x" # set this to the node version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install and build
        run: |
          npm install @kolkov/ngx-gallery --legacy-peer-deps
          npm install ngx-spinner --legacy-peer-deps  
          npm install ng2-file-upload@next --legacy-peer-deps
          npm install --legacy-peer-deps
          npm run build --production

      - name: "Deploy to Azure WebApp"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DATINGAPP_GUI }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
